#!/usr/bin/env python3
"""
scripts/export_tables.py
=========================
Export evaluation metrics into paper-ready formats:
  - LaTeX booktabs tables (Table 2, Table 3, Table 4)
  - Markdown tables (README / supplementary material)
  - CSV (for plotting / spreadsheet analysis)
  - Consolidated JSON (all tables in one file)

Reads from results/ produced by run_evaluation.py.

Usage
-----
    # Export from default results directory
    python scripts/export_tables.py

    # Custom results directory
    python scripts/export_tables.py --results results/eval_run_01/

    # Export only specific formats
    python scripts/export_tables.py --formats latex markdown

    # Override output directory
    python scripts/export_tables.py --output paper/tables/

    # Include ablation table
    python scripts/export_tables.py --ablation

    # Print all tables to stdout (no file writes)
    python scripts/export_tables.py --print-only

Exit codes: 0 success | 2 fatal
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
import time
from io import StringIO
from pathlib import Path
from typing import Any

_ROOT = Path(__file__).resolve().parent.parent
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

from src.utils.logger import get_logger

log = get_logger("export_tables")

DEFAULT_RESULTS = _ROOT / "results"
DEFAULT_OUTPUT  = _ROOT / "paper" / "tables"
PLATFORMS       = ("splunk", "qradar", "elastic", "sentinel", "wazuh")


# ─────────────────────────────────────────────────────────────────────────────
# Result loading
# ─────────────────────────────────────────────────────────────────────────────

def _find_latest_tables(results_dir: Path) -> tuple[list[dict], list[dict], list[dict]]:
    """
    Locate the most recent table JSON files in results_dir.
    Returns (table2_rows, table3_rows, table4_rows).
    """
    def _latest(pattern: str) -> Path | None:
        candidates = sorted(results_dir.glob(pattern), reverse=True)
        return candidates[0] if candidates else None

    t2_path = _latest("table2_main_results_*.json")
    t3_path = _latest("table3_error_analysis_*.json")
    t4_path = _latest("table4_ablation_*.json")

    # Fall back to combined file
    combined = _latest("all_tables_*.json")
    if combined and (not t2_path or not t3_path):
        data = json.loads(combined.read_text())
        return data.get("table2", []), data.get("table3", []), data.get("table4", [])

    t2 = json.loads(t2_path.read_text()) if t2_path else []
    t3 = json.loads(t3_path.read_text()) if t3_path else []
    t4 = json.loads(t4_path.read_text()) if t4_path else []
    return t2, t3, t4


# ─────────────────────────────────────────────────────────────────────────────
# LaTeX exporters
# ─────────────────────────────────────────────────────────────────────────────

def _table2_latex(rows: list[dict]) -> str:
    lines = [
        r"% Table 2 — Main Evaluation Results",
        r"% Generated by NL-SIEM export_tables.py",
        r"\begin{table}[t]",
        r"\centering",
        r"\setlength{\tabcolsep}{4pt}",
        r"\caption{",
        r"    Evaluation results for NL-SIEM across five SIEM platforms.",
        r"    \emph{Valid\%}: syntactic validity; \emph{Sem.}: semantic score;",
        r"    \emph{BLEU}: BLEU-4; \emph{F1}: field-match F1;",
        r"    \emph{Exact\%}: exact execution match.",
        r"}",
        r"\label{tab:main_results}",
        r"\begin{tabular}{l r r r r r r r}",
        r"\toprule",
        r"\textbf{Platform} & \textbf{Valid\%} & \textbf{Sem.} & \textbf{BLEU} & "
        r"\textbf{ROUGE-L} & \textbf{F1} & \textbf{Exact\%} & \textbf{Recall\%} \\",
        r"\midrule",
    ]
    for r in rows:
        is_avg = r.get("platform") == "MACRO-AVG"
        if is_avg:
            lines.append(r"\midrule")
        bold = r"\textbf{" if is_avg else ""
        endb = r"}"          if is_avg else ""
        line = (
            f"{bold}{r.get('platform','?')}{endb} & "
            f"{bold}{r.get('validity_%','0.0')}{endb} & "
            f"{bold}{r.get('semantic_score','0.0000')}{endb} & "
            f"{bold}{r.get('bleu','0.0000')}{endb} & "
            f"{bold}{r.get('rouge_l','0.0000')}{endb} & "
            f"{bold}{r.get('field_f1','0.0000')}{endb} & "
            f"{bold}{r.get('exact_match_%','0.0')}{endb} & "
            f"{bold}{r.get('recall_match_%','0.0')}{endb} \\\\"
        )
        lines.append(line)
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]
    return "\n".join(lines) + "\n"


def _table3_latex(rows: list[dict]) -> str:
    lines = [
        r"% Table 3 — Error Analysis",
        r"% Generated by NL-SIEM export_tables.py",
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{",
        r"    Error taxonomy for NL-SIEM translation failures.",
        r"    \emph{Err\%}: overall error rate; columns show per-category counts.",
        r"}",
        r"\label{tab:error_analysis}",
        r"\begin{tabular}{l r r r r r r r l}",
        r"\toprule",
        r"\textbf{Platform} & \textbf{Err\%} & \textbf{Syn} & \textbf{Fld} & "
        r"\textbf{Op} & \textbf{Log} & \textbf{Tmp} & \textbf{Plt} & \textbf{Top Error} \\",
        r"\midrule",
    ]
    for r in rows:
        line = (
            f"{r.get('platform','?')} & "
            f"{r.get('error_rate_%','0.0')} & "
            f"{r.get('syntax_errors',0)} & "
            f"{r.get('field_errors',0)} & "
            f"{r.get('operator_errors',0)} & "
            f"{r.get('logic_errors',0)} & "
            f"{r.get('temporal_errors',0)} & "
            f"{r.get('platform_errors',0)} & "
            f"\\texttt{{{r.get('top_error','none')}}} \\\\"
        )
        lines.append(line)
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]
    return "\n".join(lines) + "\n"


def _table4_latex(rows: list[dict]) -> str:
    if not rows:
        return "% Table 4 — Ablation (no data)\n"
    lines = [
        r"% Table 4 — Ablation Study",
        r"% Generated by NL-SIEM export_tables.py",
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{",
        r"    Ablation study: contribution of IR schema and RAG retrieval.",
        r"    A = Baseline LLM; B = IR + LLM; C = Full System (IR + RAG + Refinement).",
        r"    $\Delta$ = improvement over Condition A.",
        r"}",
        r"\label{tab:ablation}",
        r"\begin{tabular}{l l r r r r r}",
        r"\toprule",
        r"\textbf{Cond.} & \textbf{Platform} & \textbf{Valid\%} & \textbf{Sem.} & "
        r"\textbf{BLEU} & \textbf{F1} & \textbf{$\Delta$} \\",
        r"\midrule",
    ]
    current_cond = None
    for r in rows:
        cond = r.get("condition", "?")
        if cond != current_cond:
            if current_cond is not None:
                lines.append(r"\midrule")
            current_cond = cond
        label = r.get("condition_label", cond)
        delta = r.get("delta_vs_A", "0.0000")
        sign  = "+" if str(delta).startswith("0.") or str(delta) == "0.0000" else ""
        line  = (
            f"{cond} ({label[:10]}) & "
            f"{r.get('platform','?')} & "
            f"{r.get('validity_%','0.0')} & "
            f"{r.get('semantic_score','0.0000')} & "
            f"{r.get('bleu','0.0000')} & "
            f"{r.get('field_f1','0.0000')} & "
            f"{sign}{delta} \\\\"
        )
        lines.append(line)
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]
    return "\n".join(lines) + "\n"


# ─────────────────────────────────────────────────────────────────────────────
# Markdown exporters
# ─────────────────────────────────────────────────────────────────────────────

def _to_markdown(rows: list[dict], title: str) -> str:
    if not rows:
        return f"### {title}\n\n_(no data)_\n"
    cols  = list(rows[0].keys())
    lines = [f"### {title}", ""]
    lines.append("| " + " | ".join(cols) + " |")
    lines.append("| " + " | ".join(["---"] * len(cols)) + " |")
    for r in rows:
        lines.append("| " + " | ".join(str(r.get(c, "")) for c in cols) + " |")
    lines.append("")
    return "\n".join(lines)


# ─────────────────────────────────────────────────────────────────────────────
# CSV exporters
# ─────────────────────────────────────────────────────────────────────────────

def _to_csv(rows: list[dict]) -> str:
    if not rows:
        return ""
    buf  = StringIO()
    cols = list(rows[0].keys())
    w    = csv.DictWriter(buf, fieldnames=cols)
    w.writeheader()
    w.writerows(rows)
    return buf.getvalue()


# ─────────────────────────────────────────────────────────────────────────────
# Stdout printer
# ─────────────────────────────────────────────────────────────────────────────

def _print_table(title: str, rows: list[dict]) -> None:
    if not rows:
        print(f"\n{title}\n  (no data)\n")
        return
    cols   = list(rows[0].keys())
    widths = {c: max(len(c), max(len(str(r.get(c,""))) for r in rows)) for c in cols}
    sep    = "+" + "+".join("-" * (w + 2) for w in widths.values()) + "+"
    hdr    = "|" + "|".join(f" {c:<{widths[c]}} " for c in cols) + "|"
    print(f"\n{title}")
    print(sep); print(hdr); print(sep)
    for r in rows:
        print("|" + "|".join(f" {str(r.get(c,'')):<{widths[c]}} " for c in cols) + "|")
    print(sep)


# ─────────────────────────────────────────────────────────────────────────────
# Main export function
# ─────────────────────────────────────────────────────────────────────────────

def export(
    t2:         list[dict],
    t3:         list[dict],
    t4:         list[dict],
    output_dir: Path,
    formats:    list[str],
    print_only: bool,
) -> dict[str, Path]:
    """
    Export tables to all requested formats.

    Args:
        t2, t3, t4:  Table rows as plain dicts (from JSON files).
        output_dir:  Directory to write output files.
        formats:     Subset of ["latex", "markdown", "csv", "json"].
        print_only:  If True, print to stdout only.

    Returns:
        Dict of format_name → Path.
    """
    ts      = time.strftime("%Y%m%d_%H%M%S")
    paths:  dict[str, Path] = {}

    if print_only or "latex" in formats:
        t2_tex = _table2_latex(t2)
        t3_tex = _table3_latex(t3)
        t4_tex = _table4_latex(t4)
        if print_only:
            print("\n" + "=" * 64 + "  LaTeX — Table 2\n")
            print(t2_tex)
            print("=" * 64 + "  LaTeX — Table 3\n")
            print(t3_tex)
            if t4:
                print("=" * 64 + "  LaTeX — Table 4\n")
                print(t4_tex)
        if not print_only and "latex" in formats:
            output_dir.mkdir(parents=True, exist_ok=True)
            for name, content in [
                (f"table2_main_{ts}.tex",   t2_tex),
                (f"table3_errors_{ts}.tex", t3_tex),
                (f"table4_ablation_{ts}.tex", t4_tex),
            ]:
                p = output_dir / name
                p.write_text(content)
                paths[name] = p

    if print_only or "markdown" in formats:
        md = "\n".join([
            "# NL-SIEM Evaluation Results\n",
            f"_Generated: {time.strftime('%Y-%m-%d %H:%M:%S')}_\n",
            _to_markdown(t2, "Table 2 — Main Results"),
            _to_markdown(t3, "Table 3 — Error Analysis"),
            _to_markdown(t4, "Table 4 — Ablation Study") if t4 else "",
        ])
        if print_only:
            print("\n" + "=" * 64 + "  Markdown\n")
            print(md[:2000], "…" if len(md) > 2000 else "")
        if not print_only and "markdown" in formats:
            output_dir.mkdir(parents=True, exist_ok=True)
            p = output_dir / f"results_{ts}.md"
            p.write_text(md)
            paths["markdown"] = p

    if not print_only and "csv" in formats:
        output_dir.mkdir(parents=True, exist_ok=True)
        for name, rows in [("table2", t2), ("table3", t3), ("table4", t4)]:
            if rows:
                p = output_dir / f"{name}_{ts}.csv"
                p.write_text(_to_csv(rows))
                paths[f"{name}_csv"] = p

    if not print_only and "json" in formats:
        output_dir.mkdir(parents=True, exist_ok=True)
        p = output_dir / f"all_tables_{ts}.json"
        p.write_text(json.dumps({"table2": t2, "table3": t3, "table4": t4,
                                  "generated_at": ts}, indent=2))
        paths["json"] = p

    if print_only:
        print("\n──  Stdout export complete  ──\n")
        _print_table("TABLE 2 — Main Results",  t2)
        _print_table("TABLE 3 — Error Analysis", t3)
        if t4:
            _print_table("TABLE 4 — Ablation",  t4)

    return paths


# ─────────────────────────────────────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────────────────────────────────────

def main() -> int:
    parser = argparse.ArgumentParser(
        description="Export evaluation tables to LaTeX / Markdown / CSV / JSON.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("--results",    type=Path, default=DEFAULT_RESULTS,
                        help="Directory containing run_evaluation.py output files")
    parser.add_argument("--output",     type=Path, default=DEFAULT_OUTPUT,
                        help="Directory to write exported files")
    parser.add_argument("--formats",    nargs="+",
                        choices=["latex", "markdown", "csv", "json"],
                        default=["latex", "markdown", "csv", "json"],
                        help="Output formats to generate")
    parser.add_argument("--print-only", action="store_true",
                        help="Print to stdout; do not write files")
    parser.add_argument("--ablation",   action="store_true",
                        help="Include Table 4 ablation (requires ablation data)")
    parser.add_argument("--quiet",      action="store_true")
    args = parser.parse_args()

    if not args.quiet:
        print("\n" + "=" * 64)
        print("  NL-SIEM  |  Table Exporter")
        print("=" * 64)
        print(f"  results : {args.results}")
        print(f"  output  : {args.output}")
        print(f"  formats : {args.formats}\n")

    # Load table data
    if not args.results.exists():
        print(f"[ERROR]  Results directory not found: {args.results}\n"
              f"         Run: python scripts/run_evaluation.py", file=sys.stderr)
        return 2

    try:
        t2, t3, t4 = _find_latest_tables(args.results)
    except Exception as exc:
        print(f"[ERROR]  Could not load tables: {exc}", file=sys.stderr)
        log.exception("Table loading failed")
        return 2

    if not t2 and not t3:
        print("[ERROR]  No table data found in results directory.", file=sys.stderr)
        return 2

    if not args.ablation:
        t4 = []

    if not args.quiet:
        print(f"  Loaded: Table2={len(t2)} rows, Table3={len(t3)} rows, Table4={len(t4)} rows")

    # Export
    try:
        paths = export(
            t2         = t2,
            t3         = t3,
            t4         = t4,
            output_dir = args.output,
            formats    = args.formats,
            print_only = args.print_only,
        )
    except Exception as exc:
        log.exception("Export failed")
        print(f"[ERROR]  {exc}", file=sys.stderr)
        return 2

    if not args.print_only and not args.quiet:
        print(f"\n[OK]  {len(paths)} files written to: {args.output}")
        for name, p in paths.items():
            print(f"       {name:<30} → {p.name}")
        print()

    return 0


if __name__ == "__main__":
    sys.exit(main())